#!/bin/sh
### BEGIN INIT INFO
# Provides:          gunicorn-ddns
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Gunicorn app server for ThatPanda DDNS
### END INIT INFO

RUNDIR=/var/run/gunicorn-ddns
SOCKETFILE=$RUNDIR/gunicorn.sock
PIDFILE=$RUNDIR/gunicorn.pid
LOGFILE=/var/log/gunicorn-ddns.log

APP_DIR=/var/vhost/ddns.thatpanda.com/
SCRIPT="bash -ec 'cd $APP_DIR; . python_env/bin/activate; gunicorn ddns_project.wsgi:application -D -w 4 -b unix:$SOCKETFILE'"
RUNAS=www-data

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  mkdir -p "$RUNDIR"
  touch "$LOGFILE" "$PIDFILE"
  chown "$RUNAS" "$RUNDIR" "$LOGFILE"
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f gunicorn-ddns remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac

